trigger:
- main

stages:
- stage: Build
  jobs:
  - job: J1
    pool:
      vmImage: ubuntu-22.04
    steps:
    - script: |
        dotnet publish --os linux --arch x64 /t:PublishContainer
      workingDirectory: $(sourceDir)/modules/$(MODULE_NAME)
      displayName: 'Build Docker Image'
    - script: |
        # Obtener el valor actual de la versión (MODULE_VERSION)
        echo "Current MODULE_VERSION: $(MODULE_VERSION)"
        # Extraer el último número antes de '-amd64' y convertirlo a un número
        VERSION_PARTS=$(echo $(MODULE_VERSION) | sed 's/-amd64//g' | tr '.' ' ')  # Convertir la versión en partes
        VERSION_ARRAY=($VERSION_PARTS)  # Crear un array con las partes de la versión
        # Incrementar el último número (el número de la versión mayor/minor)
        LAST_PART=${VERSION_ARRAY[2]}  # Obtener la última parte (la que queremos incrementar)
        NEW_LAST_PART=$((LAST_PART + 1))  # Incrementar la última parte
        # Reconstruir la nueva versión
        NEW_MODULE_VERSION="${VERSION_ARRAY[0]}.${VERSION_ARRAY[1]}.$NEW_LAST_PART-amd64"  # Reconstruir la versión completa
        # Establecer la nueva versión como variable en el pipeline
        echo "New MODULE_VERSION: $NEW_MODULE_VERSION"
        echo "##vso[task.setvariable variable=MODULE_VERSION]$NEW_MODULE_VERSION"  # Actualizar la variable MODULE_VERSION
      displayName: 'Incrementar MODULE_VERSION'
    - script: |
        docker login -u $(CONTAINER_REGISTRY_USERNAME) -p $(CONTAINER_REGISTRY_PASSWORD) $(CONTAINER_REGISTRY_ADDRESS)
        docker tag $(MODULE_NAME) $(CONTAINER_REGISTRY_ADDRESS)/$(MODULE_NAME):$(MODULE_VERSION)
        docker push $(CONTAINER_REGISTRY_ADDRESS)/$(MODULE_NAME):$(MODULE_VERSION)
      workingDirectory: $(sourceDir)
      displayName: 'Push Docker Image'

- stage: Release
  jobs:
  - job: J2
    pool:
      vmImage: ubuntu-22.04
    steps:
    - script: |
        sudo apt install software-properties-common -y
        sudo add-apt-repository ppa:deadsnakes/ppa -y
        sudo apt install python3.9 -y
        sudo apt install python3.9-distutils -y
        curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        python3.9 get-pip.py
        python3.9 -m pip install -U iotedgedev pyOpenSSL==22.0.0 urllib3==1.22 requests
      workingDirectory: $(sourceDir)
      displayName: 'Install Python & iotedgedev'

    - task: AzureIoTEdge@2
      inputs:
        action: 'Generate deployment manifest'
        templateFilePath: '$(sourceDir)/deployment.template.json'
        defaultPlatform: 'amd64'
        deploymentManifestOutputPath: '$(System.DefaultWorkingDirectory)/config/deployment.json'
        validateGeneratedDeploymentManifest: 'true'
      displayName: 'Generate Deployment manifest'

    - task: AzureIoTEdge@2
      inputs:
        action: 'Deploy to IoT Edge devices'
        deploymentFilePath: '$(System.DefaultWorkingDirectory)/config/deployment.json'
        azureSubscription: 'Azure for Students(1)(dabf653f-69aa-4b1f-b3ca-377f7318dddf)'
        iothubname: 'DiegoIoTHubTutorial'
        deploymentid: '$(System.TeamProject)-devops-deployment'
        priority: '0'
        deviceOption: 'Single Device'
        deviceId: 'diegoEdgeDevice3'
      displayName: 'Deploy to IoT Edge devices'